Added checks

diff --git a/expose-an-app-using-a-definition-file/check-kubernetes b/expose-an-app-using-a-definition-file/check-kubernetes
--- a/expose-an-app-using-a-definition-file/check-kubernetes
+++ b/expose-an-app-using-a-definition-file/check-kubernetes
@@ -1,15 +1,22 @@
-#!/bin/sh
-#
-# This is a sample check script. Rename this file to check-$CONTAINER
-# (where $container is the name of the container as defined in your config.yml),
-# and replace this content with your own script.
-#
-# This script will be run when you check the challenge.
-#
-# Remember that the exit code is important. See the documentation
-# for more information.
-#
+#!/bin/bash
+COMMAND=$(cat /root/.bash_history | grep -e "^kubectl create -f nginx-service.yml" -e "^kubectl apply -f nginx-service.yml" | wc -l)
+if [ $COMMAND -eq 0 ]; then
+  echo "FAIL: the service definition file was not deployed."
+  exit 1
+fi
 
-echo "This is the check script"
+SERVICE=$(kubectl get svc nginx -o json)
+
+PORT=$(echo $SERVICE | jq -r '.spec.ports[0].port')
+if [ "$PORT" != "30000" ]; then
+  echo "FAIL: The exposed port isn't set to 30000."
+  exit 1
+fi
+
+TARGETPORT=$(echo $SERVICE | jq -r '.spec.ports[0].targetPort')
+if [ "$TARGETPORT" != "80" ]; then
+  echo "FAIL: The target port isn't set correctly. Use kubectl describe on the nginx deployment to get the correct port."
+  exit 1
+fi
 
 exit 0
